---
detectors:
  BooleanParameter:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: false
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyStatements:
    enabled: false
  UnusedParameters:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UtilityFunction:
    enabled: false
