AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/**/*'
Gemspec/OrderedDependencies:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
LineLength:
  Max: 100
Lint/RescueException:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
